#!/bin/bash
fallback(){
        echo -e "\033[31;1mInstallation failed.\033[;0m"
        echo -e "Creating a shell for debuging. Good luck :D"
        PS1="\[\033[32;1m\]>>>\[\033[;0m\]" /bin/bash --norc --noprofile
        if [[ $$ -eq 0 ]] ; then
            echo o > /proc/sysrq-trigger
        else
            exit 1
        fi
}
selectdisk=0
createmenu=0
disk="sdk"
USBKEYS=($(
                xargs -n1 readlink < <(echo /sys/block/*) |
                sed -ne 's+^.*/usb[0-9].*/\([^/]*\)$+/sys/block/\1/device/uevent+p' |
                xargs grep -H ^DRIVER=sd |
                sed s/device.uevent.*$/size/ |
                xargs grep -Hv ^0$ |
                cut -d / -f 4                 ))
#echo ${USBKEYS[@]}
USBKEYS+=("sr0")
for item in $(ls /sys/block/)
do
found="0"
	for dev in ${USBKEYS[@]} ;do
	#echo ${item}-${dev}
		if [ "$item" == "$dev" ]
        	then		
			found="1"
        	fi       	
	done
	
	if [ "$found" == "0" ]
        	then
        		#disk+=("$item")
        		disk[${#disk[@]}]="$item"
        	fi        
done



if [ ${#disk[@]} == 1 ]
then
echo "Tek Sabit Diskiniz var: ${disk[0]}"
selectdisk=${disk[0]}
else
echo "Birden Fazla Sabit Diskiniz Var : ${disk[@]}"
echo "Kurulum İşlemini Canlı Yükle Seçeneğinden Yapınız.."
fallback
fi
echo "Sabit Diskiniz  $selectdisk"

