install:
	install script.sh /etc/initramfs-tools/scripts/init-bottom/deepfreeze.sh
	install hook.sh /etc/initramfs-tools/hooks/deepfreeze.sh
	install config.ini /etc/deepfreeze.conf
uninstall:
	rm -f /etc/initramfs-tools/scripts/init-bottom/deepfreeze.sh
	rm -f /etc/initramfs-tools/hooks/deepfreeze.sh
	rm -f /etc/deepfreeze.conf
